# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Build APP:Backend
      working-directory: Backend
      run: go build -v ./...

    - name: Build APP:Scheduler
      working-directory: Scheduler
      run: go build -v ./...

    - name: Build APP:Scheduler:daily_update
      working-directory: Scheduler/daily_status_update
      run: go build -v daily_update.go
